//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestRest.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestRest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap flecha_der {
            get {
                object obj = ResourceManager.GetObject("flecha_der", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flecha_izq {
            get {
                object obj = ResourceManager.GetObject("flecha_izq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon GestRestIcon {
            get {
                object obj = ResourceManager.GetObject("GestRestIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        internal static string rxAbril {
            get {
                return ResourceManager.GetString("rxAbril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agost.
        /// </summary>
        internal static string rxAgosto {
            get {
                return ResourceManager.GetString("rxAgosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desembre.
        /// </summary>
        internal static string rxDiciembre {
            get {
                return ResourceManager.GetString("rxDiciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diumenge.
        /// </summary>
        internal static string rxDomingo {
            get {
                return ResourceManager.GetString("rxDomingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gener.
        /// </summary>
        internal static string rxEnero {
            get {
                return ResourceManager.GetString("rxEnero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrer.
        /// </summary>
        internal static string rxFebrero {
            get {
                return ResourceManager.GetString("rxFebrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dijous.
        /// </summary>
        internal static string rxJueves {
            get {
                return ResourceManager.GetString("rxJueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juliol.
        /// </summary>
        internal static string rxJulio {
            get {
                return ResourceManager.GetString("rxJulio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juny.
        /// </summary>
        internal static string rxJunio {
            get {
                return ResourceManager.GetString("rxJunio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dilluns.
        /// </summary>
        internal static string rxLunes {
            get {
                return ResourceManager.GetString("rxLunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dimarts.
        /// </summary>
        internal static string rxMartes {
            get {
                return ResourceManager.GetString("rxMartes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Març.
        /// </summary>
        internal static string rxMarzo {
            get {
                return ResourceManager.GetString("rxMarzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maig.
        /// </summary>
        internal static string rxMayo {
            get {
                return ResourceManager.GetString("rxMayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dimecres.
        /// </summary>
        internal static string rxMiercoles {
            get {
                return ResourceManager.GetString("rxMiercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a €.
        /// </summary>
        internal static string rxMoneda {
            get {
                return ResourceManager.GetString("rxMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novembre.
        /// </summary>
        internal static string rxNoviembre {
            get {
                return ResourceManager.GetString("rxNoviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        internal static string rxOctubre {
            get {
                return ResourceManager.GetString("rxOctubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dissabte.
        /// </summary>
        internal static string rxSabado {
            get {
                return ResourceManager.GetString("rxSabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setembre.
        /// </summary>
        internal static string rxSetiembre {
            get {
                return ResourceManager.GetString("rxSetiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divendres.
        /// </summary>
        internal static string rxViernes {
            get {
                return ResourceManager.GetString("rxViernes", resourceCulture);
            }
        }
    }
}
